# image: node:latest

# workflow:
#   rules:
#     - if: $CI_PIPELINE_SOURCE == "merge_request_event"

# Frontend tests:
#   stage: test
#   variables:
#     GIT_CHECKOUT: "true"
#   script:
#     - export PATH=/home/ubuntu/.nvm/versions/node/v10.16.3/bin/:$PATH
#     - cd frontend
#     - npm ci
#     - npm run test

# TEST FOR PYTHON BACKEND
image: python:latest

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"

before_script:
  - python3 -m venv venv
  - source venv/bin/activate
  - pwd
  - pip install -r requirements.txt

Backend tests:
  stage: test
  variables:
    GIT_CHECKOUT: "true"
  script:
    - cd backend
    - pytest
