image: ubuntu:latest

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"

stages:
  - test frontend
  - test backend

Frontend tests:
  stage: test frontend
  image: node:latest
  variables:
    GIT_CHECKOUT: "true"
  script:
    - cd frontend
    - npm ci
    - npm run test

Backend tests:
  stage: test backend
  image: python:latest
  variables:
    GIT_CHECKOUT: "true"
  script:
    - cd backend
    - python3 -m venv venv
    - source venv/bin/activate
    - pip install -r requirements.txt
    - pytest
# image: node:latest

# workflow:
#   rules:
#     - if: $CI_PIPELINE_SOURCE == "merge_request_event"

# before_script:
#   - cd ..
#   - pwd
#   - cd frontend

# Frontend tests:
#   stage: test
#   variables:
#     GIT_CHECKOUT: "true"
#   script:
#     - export PATH=/home/ubuntu/.nvm/versions/node/v10.16.3/bin/:$PATH
#     - npm ci
#     - npm run test

# # TEST FOR BACKEND
# image: python:latest

# workflow:
#   rules:
#     - if: $CI_PIPELINE_SOURCE == "merge_request_event"

# before_script:
#   - cd backend
#   - python3 -m venv venv
#   - source venv/bin/activate
#   - pip install -r requirements.txt

# Backend tests:
#   stage: test
#   variables:
#     GIT_CHECKOUT: "true"
#   script:
#     - pytest
