image: node:latest

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"

Frontend tests:
  stage: test
  variables:
    GIT_CHECKOUT: "true"
  script:
    - whoami
    - locate npm
    - echo $PATH
    - which npm
    - cd frontend
    - npm ci
    - echo "Running frontend tests..."
    - npm run test
